In [1]:
import torch

In [2]:
x = torch.empty(5,3)
x

tensor([[-2.5362e-26,  3.0785e-41,  2.7465e-43],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.5799e-41,  1.8788e+31,  1.7220e+22],
        [ 7.4814e+20,  6.7055e+22,  1.0529e-11]])

In [43]:
x = torch.rand(5,3)
x

tensor([[0.5064, 0.7890, 0.8424],
        [0.0597, 0.1209, 0.7032],
        [0.2781, 0.3741, 0.2379],
        [0.8151, 0.6655, 0.2156],
        [0.1345, 0.3079, 0.7089]])

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [38]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [40]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.3154,  0.4852, -0.5413],
        [ 1.8557,  0.4100, -1.4662],
        [-0.4475, -1.2453, -0.1441],
        [ 0.4602,  1.0495, -0.0288],
        [-2.2683,  1.6927,  0.4342]])

In [49]:
y = x.copy_(x)

In [50]:
y

tensor([[0.5064, 0.7890, 0.8424],
        [0.0597, 0.1209, 0.7032],
        [0.2781, 0.3741, 0.2379],
        [0.8151, 0.6655, 0.2156],
        [0.1345, 0.3079, 0.7089]])

In [53]:
a = y.numpy()

In [54]:
a

array([[0.5063534 , 0.78904337, 0.8423985 ],
       [0.05966693, 0.12091929, 0.7032049 ],
       [0.27812994, 0.37414646, 0.23793077],
       [0.81510115, 0.66550994, 0.21559489],
       [0.13451463, 0.3079239 , 0.708936  ]], dtype=float32)

In [55]:
b = torch.from_numpy(a)

In [56]:
b

tensor([[0.5064, 0.7890, 0.8424],
        [0.0597, 0.1209, 0.7032],
        [0.2781, 0.3741, 0.2379],
        [0.8151, 0.6655, 0.2156],
        [0.1345, 0.3079, 0.7089]])

In [58]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(a,device='device')
    

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not numpy.ndarray