In [1]:
import torch

# .requires_grad
* True로 설정 시 tensor에서 이뤄진 모든 연산을 추적  
* 계산 완료 후 **.backward()** 호출하여 모든 gradient를 자동으로 계산할 수 있음  
* 이 Tensor의 변화도는 **.grad** 속성에 누적됨

In [2]:
x = torch.ones(2,2,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x+2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
print(y.grad_fn)

In [7]:
z = y*y*3
out = z.mean()

In [8]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a=torch.randn(2,2)
a=((a*3)/(a-1))

In [13]:
print(a.requires_grad)

False


In [14]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [15]:
b = (a*a).sum()
print(b.grad_fn)

## Gradient (변화도)
* back-propagation

In [16]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [17]:
out.backward()

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### Vector-Jacobian mul    

In [35]:
x = torch.randn(3,requires_grad=True)

In [36]:
x

tensor([-1.7770, -2.1594, -1.6350], requires_grad=True)

In [37]:
y = x*2

In [38]:
y

tensor([-3.5539, -4.3188, -3.2700], grad_fn=<MulBackward0>)

In [25]:
while y.data.norm()<1000:
    y = y*2

In [26]:
y

tensor([1383.1249,  -86.3572,   34.5008], grad_fn=<MulBackward0>)